[package]
name = "pdx-atlas"
version = "0.1.0"
edition = "2024"

[dependencies]
pdx-native = { git = "https://github.com/pdx-foundry/native.git", rev = "866e2ea34b7b976b5cd91c5e2306af3fef3bdd12" }
pdxscript = { git = "https://github.com/pdx-foundry/pdxscript-rs.git", rev = "ccb681ac10af4a4efb21ec42450b1a04d2d8500a" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["rt", "time", "macros"] }

[dev-dependencies]
jsonschema = { version = "0.56", default-features = false }
tempfile = "3"
