//! Trim a full recording to the answers that Atlas's recorded tests read.
//!
//! A full recording holds every registry and command of the build; the tests read a few. This
//! keeps the listed registries, commands and loaded modifiers, removes the other per-registry and
//! per-command answers, and leaves each kept answer's source, completeness and gaps unchanged.
//! Running it again changes nothing.
use pdx_native::{Answer, Declaration, Error, LoadedModifiers, Registry};
use serde::{Serialize, de::DeserializeOwned};
use std::{
    fs,
    path::{Path, PathBuf},
};

/// Registries whose fields, derived names and modifier families the tests read.
const REGISTRIES: &[&str] = &[
    "common/buildings",
    "common/council_agendas",
    "common/economic_categories",
    "common/pop_jobs",
    "common/relics",
    "common/technology",
    "common/tradition_categories",
    "common/traditions",
    "interface/resource_groups",
    "map/galaxy",
];

/// Effects and triggers whose declarations and grammars the tests read.
const EFFECTS: &[&str] = &["add_age", "add_building", "set_variable"];
const TRIGGERS: &[&str] = &["has_modifier", "is_mercenary"];

/// Loaded modifiers that the tests read: declared with equal tags, declared with different
/// tags, unexplained, and generated by the `common/pop_jobs` family for `miner`.
const LOADED_MODIFIERS: &[&str] = &[
    "pop_happiness",
    "gdf_ship_alloys_cost_mult",
    "shipclass_military_build_cost_mult",
    "job_miner_add",
];
const POP_JOB_ITEMS: &[&str] = &["miner"];

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut args = std::env::args_os().skip(1);
    let recording = PathBuf::from(args.next().ok_or("expected a recording directory")?);
    if args.next().is_some() {
        return Err("expected only a recording directory".into());
    }

    edit::<Vec<Registry>>(&recording.join("registries.json"), |registries| {
        registries.retain(|registry| REGISTRIES.contains(&registry.name.as_str()));
    })?;
    for question in ["registry_fields", "derived_names", "modifier_families"] {
        keep_files(&recording.join(question), REGISTRIES)?;
    }

    for (kind, names) in [("effect", EFFECTS), ("trigger", TRIGGERS)] {
        edit::<Vec<Declaration>>(
            &recording.join(format!("declarations/{kind}.json")),
            |declarations| {
                declarations.retain(|declaration| names.contains(&declaration.name.as_str()));
            },
        )?;
        keep_files(&recording.join(format!("command_grammar/{kind}")), names)?;
    }

    edit::<LoadedModifiers>(&recording.join("loaded_modifiers.json"), |loaded| {
        loaded
            .modifiers
            .retain(|modifier| LOADED_MODIFIERS.contains(&modifier.name.as_str()));
        loaded
            .registry_items
            .retain(|registry, _| registry == "common/pop_jobs");
        for items in loaded.registry_items.values_mut() {
            items.retain(|item| POP_JOB_ITEMS.contains(&item.as_str()));
        }
    })?;

    Ok(())
}

/// Rewrite one recorded answer's value, in the form Native writes it.
fn edit<T: Serialize + DeserializeOwned>(
    path: &Path,
    change: impl FnOnce(&mut T),
) -> Result<(), Box<dyn std::error::Error>> {
    let mut recorded: Result<Answer<T>, Error> = serde_json::from_slice(&fs::read(path)?)?;
    let answer = recorded
        .as_mut()
        .map_err(|error| format!("{} holds an error: {error}", path.display()))?;
    change(&mut answer.value);

    let mut bytes = serde_json::to_vec_pretty(&recorded)?;
    bytes.push(b'\n');
    fs::write(path, bytes)?;

    Ok(())
}

/// Remove every `{subject}.json` below `root` whose subject is not in `keep`, and the
/// directories that become empty.
fn keep_files(root: &Path, keep: &[&str]) -> Result<(), Box<dyn std::error::Error>> {
    remove_unkept(root, root, keep)
}

fn remove_unkept(
    root: &Path,
    directory: &Path,
    keep: &[&str],
) -> Result<(), Box<dyn std::error::Error>> {
    for entry in fs::read_dir(directory)? {
        let path = entry?.path();
        if path.is_dir() {
            remove_unkept(root, &path, keep)?;
            if fs::read_dir(&path)?.next().is_none() {
                fs::remove_dir(&path)?;
            }
            continue;
        }

        let subject = path.strip_prefix(root)?.with_extension("");
        if !keep.contains(&subject.to_string_lossy().as_ref()) {
            fs::remove_file(&path)?;
        }
    }

    Ok(())
}
